import React, { useState } from 'react';
import { Key, ArrowLeft, ShieldCheck, Globe, Warehouse, Mail, Lock, ShieldAlert, CheckCircle2, RefreshCw, Eye, EyeOff, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { AccountVerification } from './AccountVerification';

interface AccountAccessProps {
  onBack: () => void;
  onAdminSuccess?: (user: any, token: string) => void;
  t: any;
}

export function AccountAccess({ onBack, onAdminSuccess, t }: AccountAccessProps) {
  const [view, setView] = useState<'selection' | 'verification' | 'admin-login'>('selection');
  const [verificationType, setVerificationType] = useState<string>('');
  const [adminKey, setAdminKey] = useState('');

  // Two-step auth credentials states
  const [emailInput, setEmailInput] = useState('');
  const [passwordInput, setPasswordInput] = useState('');
  const [otpInput, setOtpInput] = useState('');
  const [step, setStep] = useState<'credentials' | 'otp'>('credentials');
  const [showPassword, setShowPassword] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [loginError, setLoginError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleVerify = (type: string) => {
    setVerificationType(type);
    setView('verification');
  };

  const handleAdminVerify = () => {
    setView('admin-login');
  };

  const handleCredentialLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!emailInput.trim() || !passwordInput.trim()) {
      setLoginError('অনুগ্রহ করে ইউজারনেম এবং পাসওয়ার্ড দুটোই প্রদান করুন।');
      return;
    }
    setLoginError('');
    setIsSubmitting(true);
    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: emailInput.trim(), password: passwordInput.trim() })
      });
      const data = await response.json();
      if (response.ok && data.success) {
        if (data.requires_otp) {
          setStep('otp');
          if (data.auto_otp) {
            setAutoGeneratedCode(data.auto_otp);
          }
        } else {
          // Direct login successful (e.g. Editor role validated!)
          onAdminSuccess?.(data.user, data.token);
        }
      } else {
        setLoginError(data.error || 'লগইন করতে ব্যর্থ! অনুগ্রহ করে সঠিক তথ্য প্রদান করুন।');
      }
    } catch (err) {
      setLoginError('সার্ভারে যোগাযোগ করতে ব্যর্থ হয়েছে। দয়া করে ইন্টারনেট চেক করুন।');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleOTPVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!otpInput.trim()) {
      setLoginError('অনুগ্রহ করে ওটিপি (OTP Code)পাসওয়ার্ড কোডটি দিন।');
      return;
    }
    setLoginError('');
    setIsSubmitting(true);
    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          email: emailInput.trim(), 
          password: passwordInput.trim(), 
          otp_code: otpInput.trim() 
        })
      });
      const data = await response.json();
      if (response.ok && data.success) {
        onAdminSuccess?.(data.user, data.token);
      } else {
        setLoginError(data.error || 'ভুল অথবা মেয়াদোত্তীর্ণ ওটিপি কোড!');
      }
    } catch (err) {
      setLoginError('সার্ভার কানেকশন এরর! পুনরায় চেষ্টা করুন।');
    } finally {
      setIsSubmitting(false);
    }
  };

  const checkAdminKey = () => {
    if (adminKey === 'PTS') {
      // Simulate mapping back to default Admin user
      onAdminSuccess?.({ id: 1, username: 'usplabonadmin@gmail.com', email: 'usplabonadmin@gmail.com', role: 'Admin', display_name: 'MD Plabon Biswas' }, 'token_pts_quick');
    } else {
      alert('ভুল এডমিন কি! সঠিক কি দিয়ে পুনরায় চেষ্টা করুন।');
    }
  };

  if (view === 'verification') {
    return (
      <div className="relative min-h-screen bg-[#f4f7f6]">
        <button 
          onClick={() => setView('selection')}
          className="fixed top-6 left-6 z-[2000] flex items-center gap-2 px-4 py-2 bg-white text-primary rounded-full font-bold shadow-xl hover:-translate-y-1 transition-all"
        >
          <ArrowLeft size={18} />
          <span>Back</span>
        </button>
        <AccountVerification 
          title={verificationType === 'global' ? 'Global Account Verification' : 'Warehouse Account Verification'}
          onVerify={(data) => {
            alert('ভেরিফিকেশন সফল হয়েছে!');
            setView('selection');
          }} 
        />
      </div>
    );
  }

  if (view === 'admin-login') {
    return (
      <div className="min-h-screen bg-[#f4f7f6] flex flex-col items-center justify-center p-4">
        <button 
          onClick={() => {
            setView('selection');
            setStep('credentials');
            setLoginError('');
            setEmailInput('');
            setPasswordInput('');
            setOtpInput('');
          }}
          className="mb-6 flex items-center gap-2 px-5 py-2 bg-white text-primary rounded-full font-bold shadow-md hover:-translate-y-1 transition-all self-start md:ml-[10%]"
        >
          <ArrowLeft size={18} />
          <span>Back to Selection</span>
        </button>
        <div className="w-full max-w-lg">
          <h2 className="text-2xl font-black text-center mb-6 text-gray-800 tracking-tight flex items-center justify-center gap-2">
            <ShieldCheck className="text-indigo-600 animate-pulse" />
            Fortress Premium Login Portal
          </h2>
          <div className="bg-white p-6 md:p-8 rounded-3xl shadow-xl border border-gray-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-indigo-500 via-pink-500 to-purple-600" />
            
            <AnimatePresence mode="wait">
              {step === 'credentials' ? (
                <motion.form 
                  key="form-credentials"
                  initial={{ opacity: 0, x: -15 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 15 }}
                  onSubmit={handleCredentialLogin}
                  className="space-y-4"
                >
                  <div className="text-center mb-4">
                    <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-2xl flex items-center justify-center mx-auto mb-3 shadow-lg">
                      <Key size={30} className="text-white" />
                    </div>
                    <p className="text-gray-850 font-black text-sm">প্যানেলে প্রবেশের জন্য ক্রেডেনশিয়াল দিন</p>
                    <p className="text-xs text-gray-400 mt-1">রোল বেসড এক্সেস সিস্টেম (Admin OTP Enabled)</p>
                  </div>

                  {loginError && (
                    <div className="bg-red-50 border-l-4 border-red-500 p-3 rounded-lg text-xs font-bold text-red-650 flex items-start gap-2">
                      <ShieldAlert size={14} className="shrink-0 mt-0.5" />
                      <span>{loginError}</span>
                    </div>
                  )}

                  <div className="space-y-1">
                    <label className="block text-xs font-bold text-gray-650 uppercase tracking-wider">Username or Email</label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                        <Mail size={16} />
                      </div>
                      <input 
                        type="text"
                        required
                        placeholder="E.g., usplabonadmin@gmail.com"
                        value={emailInput}
                        onChange={(e) => setEmailInput(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 rounded-xl text-sm outline-none font-semibold text-gray-800 transition"
                      />
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label className="block text-xs font-bold text-gray-650 uppercase tracking-wider">Secure Password</label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                        <Lock size={16} />
                      </div>
                      <input 
                        type={showPassword ? 'text' : 'password'}
                        required
                        placeholder="••••••••••••••"
                        value={passwordInput}
                        onChange={(e) => setPasswordInput(e.target.value)}
                        className="w-full pl-10 pr-10 py-3 bg-gray-50 border border-gray-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 rounded-xl text-sm outline-none font-semibold text-gray-800 transition"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-indigo-600 transition"
                      >
                        {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                      </button>
                    </div>
                  </div>

                  <button 
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-3.5 rounded-xl font-bold text-sm shadow-md shadow-indigo-600/10 hover:shadow-indigo-600/20 active:scale-95 transition-all flex items-center justify-center gap-2"
                  >
                    {isSubmitting ? (
                      <RefreshCw size={16} className="animate-spin" />
                    ) : 'Validate Credentials & Continue'}
                  </button>

                  <div className="border-t border-gray-150 pt-3 mt-4 text-center">
                    <p className="text-[10px] text-gray-500">
                      অথবা কুইক এডমিন এক্সেস কি দিয়ে সরাসরি ঢুকতে চাইলে নিচে কি টাইপ করুন:
                    </p>
                    <div className="flex gap-2 mt-2">
                      <input 
                        type="password" 
                        placeholder="Access Key (PTS)" 
                        className="flex-1 bg-gray-50 border border-gray-200 rounded-lg px-3 py-1.5 text-xs text-center font-bold tracking-widest text-indigo-700 outline-none"
                        value={adminKey}
                        onChange={(e) => setAdminKey(e.target.value)}
                      />
                      <button
                        type="button"
                        onClick={checkAdminKey}
                        className="bg-indigo-600 hover:bg-indigo-505 text-white font-bold text-xs uppercase px-4 py-1.5 rounded-lg active:scale-95 transition"
                      >
                        Quick Check
                      </button>
                    </div>
                  </div>
                </motion.form>
              ) : (
                <motion.form 
                  key="form-otp"
                  initial={{ opacity: 0, x: 15 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -15 }}
                  onSubmit={handleOTPVerify}
                  className="space-y-4"
                >
                  <div className="text-center mb-4">
                    <div className="w-16 h-16 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-2xl flex items-center justify-center mx-auto mb-3 shadow-lg">
                      <ShieldCheck size={32} className="text-white" />
                    </div>
                    <p className="text-gray-850 font-black text-sm">রিয়েল-টাইম ২-স্টেপ ভেরিফিকেশন</p>
                    <p className="text-xs text-slate-500 mt-1">জিমেইলের সাথে কানেক্টেড কোড জেনারেট হয়ে স্ক্রিনে ব্রডকাস্ট হয়েছে</p>
                  </div>

                  {loginError && (
                    <div className="bg-red-50 border-l-4 border-red-500 p-3 rounded-lg text-xs font-bold text-red-650 flex items-start gap-2">
                      <ShieldAlert size={14} className="shrink-0 mt-0.5" />
                      <span>{loginError}</span>
                    </div>
                  )}

                  <div className="bg-emerald-50 border border-emerald-150 p-3 rounded-xl flex items-center gap-2.5">
                    <CheckCircle2 size={16} className="text-emerald-600 shrink-0" />
                    <div className="text-left text-emerald-800 text-xs font-semibold leading-normal">
                      একটি সিক্স-ডিজিট ভেরিফিকেশন কোড জেনারেট হয়েছে এবং তা ফায়ারওয়াল মনিটর মডিউলে সংযুক্ত হয়েছে।
                    </div>
                  </div>

                  {autoGeneratedCode && (
                    <div className="bg-indigo-50/70 border border-indigo-150/40 p-3 rounded-xl flex flex-col items-center justify-center">
                      <span className="text-[10px] text-indigo-550 font-black tracking-wider uppercase">সর্বশেষ জেনারেটেড ওটিপি কোড (Real-Time Code)</span>
                      <div className="flex items-center gap-3 mt-1.5">
                        <span className="text-2xl font-black font-mono tracking-widest text-indigo-650 animate-pulse">
                          {autoGeneratedCode}
                        </span>
                        <button
                          type="button"
                          onClick={() => setOtpInput(autoGeneratedCode)}
                          className="bg-indigo-600 hover:bg-indigo-505 text-white font-extrabold text-[10px] uppercase px-2.5 py-1 rounded-md active:scale-95 transition"
                        >
                          Auto Fill ⚡
                        </button>
                      </div>
                    </div>
                  )}

                  <div className="space-y-1">
                    <label className="block text-xs font-bold text-center text-gray-650 uppercase tracking-widest">৬-ডিজিট ভেরিফিকেশন ওটিপি কোড</label>
                    <input 
                      type="text"
                      maxLength={6}
                      required
                      placeholder="000000"
                      value={otpInput}
                      onChange={(e) => setOtpInput(e.target.value.replace(/\D/g, ''))}
                      className="w-full tracking-[0.4em] text-center py-3.5 bg-gray-50 border-2 border-gray-200 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 rounded-xl text-xl outline-none font-black text-indigo-700 transition"
                    />
                  </div>

                  <button 
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-gradient-to-r from-emerald-500 to-teal-500 text-white py-3.5 rounded-xl font-bold text-sm shadow-md hover:scale-[1.01] active:scale-95 transition flex items-center justify-center gap-2"
                  >
                    {isSubmitting ? (
                      <RefreshCw size={16} className="animate-spin" />
                    ) : 'Verify & Enter Administration Panel 🛡️'}
                  </button>

                  <button 
                    type="button"
                    onClick={() => {
                      setStep('credentials');
                      setLoginError('');
                      setOtpInput('');
                    }}
                    className="w-full text-slate-500 font-bold text-xs hover:text-indigo-600 transition text-center"
                  >
                    ক্রেডেনশিয়ালস এ ফিরে যান
                  </button>
                </motion.form>
              )}
            </AnimatePresence>
            
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f4f7f6] py-10 px-4">
      <div className="max-w-[1000px] mx-auto mb-6">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 px-6 py-2.5 bg-white text-primary rounded-full font-bold shadow-lg hover:-translate-y-1 transition-all"
        >
          <ArrowLeft size={20} />
          <span>Dashboard</span>
        </button>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="access-container"
      >
        <h2 className="section-title-access flex items-center justify-center gap-3 mb-10">
          <ShieldCheck size={32} />
          Account Access & Verification
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-[1000px] mx-auto">
          <VerificationOption 
            title="গ্লোবাল অ্যাকাউন্ট ভেরিফিকেশন"
            description="আপনার গ্লোবাল ড্রপশিপিং অ্যাকাউন্ট ভেরিফাই করুন"
            icon={<Globe size={40} />}
            color="bg-blue-500"
            onClick={() => handleVerify('global')}
          />
          <VerificationOption 
            title="ওয়্যারহাউজ অ্যাকাউন্ট ভেরিফিকেশন"
            description="আপনার ওয়্যারহাউজ শপিং অ্যাকাউন্ট ভেরিফাই করুন"
            icon={<Warehouse size={40} />}
            color="bg-emerald-500"
            onClick={() => handleVerify('warehouse')}
          />
          <VerificationOption 
            title="এডমিন ভেরিফিকেশন"
            description="সিস্টেম প্যানেলে প্রবেশের জন্য এডমিন ভেরিফিকেশন"
            icon={<Key size={40} />}
            color="bg-indigo-600"
            onClick={handleAdminVerify}
          />
        </div>
      </motion.div>
    </div>
  );
}

function VerificationOption({ title, description, icon, color, onClick }: any) {
  return (
    <motion.div 
      whileHover={{ y: -10 }}
      whileTap={{ scale: 0.95 }}
      onClick={onClick}
      className="bg-white p-8 rounded-[2rem] shadow-xl border border-gray-100 cursor-pointer text-center group transition-all"
    >
      <div className={`w-20 h-20 ${color} rounded-2xl flex items-center justify-center text-white mx-auto mb-6 shadow-lg group-hover:rotate-6 transition-transform`}>
        {icon}
      </div>
      <h3 className="text-xl font-bold mb-2 text-gray-800">{title}</h3>
      <p className="text-sm text-gray-500">{description}</p>
    </motion.div>
  );
}
